### ISSUE TITLE
Importer doesn't handle \date\{\today} in LaTeX

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#1152]
**What went wrong, step-by-step?**
1. Import a latex file with the command \date{\today}, ie: (rename to .tex):
[example4.txt](https://github.com/pubpub/pubpub/files/5562510/example4.txt)
1. Import will initially succeed, but when you go to import, it will fail without a warning, and the import button will keep spinning. But the /pub/api endpoint will throw a 500, and the server will complain that it has been sent a customPublishedAt date of "Invalid Date"

```
2020-11-18T20:02:53.075423+00:00 app[web.1]: SequelizeDatabaseError: invalid input syntax for type timestamp with time zone: "Invalid date"
2020-11-18T20:02:53.075433+00:00 app[web.1]:     at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
2020-11-18T20:02:53.075435+00:00 app[web.1]:     at /app/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
2020-11-18T20:02:53.075436+00:00 app[web.1]:     at bound (domain.js:420:14)
2020-11-18T20:02:53.075437+00:00 app[web.1]:     at runBound (domain.js:433:12)
2020-11-18T20:02:53.075437+00:00 app[web.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2020-11-18T20:02:53.075438+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
2020-11-18T20:02:53.075438+00:00 app[web.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
2020-11-18T20:02:53.075439+00:00 app[web.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
2020-11-18T20:02:53.075439+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
2020-11-18T20:02:53.075440+00:00 app[web.1]:     at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
2020-11-18T20:02:53.075440+00:00 app[web.1]:     at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
2020-11-18T20:02:53.075440+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
2020-11-18T20:02:53.075441+00:00 app[web.1]:     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:15:14)
2020-11-18T20:02:53.075441+00:00 app[web.1]:     at Shim.applySegment (/app/node_modules/newrelic/lib/shim/shim.js:1424:20)
2020-11-18T20:02:53.075442+00:00 app[web.1]:     at Immediate.wrapper [as _onImmediate] (/app/node_modules/newrelic/lib/shim/shim.js:2065:17)
2020-11-18T20:02:53.075442+00:00 app[web.1]:     at processImmediate (internal/timers.js:439:21)
2020-11-18T20:02:53.075443+00:00 app[web.1]:     at process.topLevelDomainCallback (domain.js:131:23)
```

**What did you expect to happen?**
The file should import, with no customPublishedAt date set.

**Comment by gabestein** [comment]
Turns out it also doesn't handle an empty `\date{}`!

**Comment by gabestein** [comment]
This was fixed in a pandoc update! https://github.com/jgm/pandoc/issues/7905
