### ISSUE TITLE
Accessing history snapshot of pub by link results in application error

### ISSUE THREAD

**Issue by howebenhowe** [pubpub/pubpub#1390]
### What went wrong, step-by-step?
1. scrolling through history of changes on [notes pub](https://notes.knowledgefutures.org/pub/p36ckkb2/draft)
2. scroll back several points in the pub history
3. copy the link to that point in history ('link here' button)
4. open link in new tab
5. broken
...

### What did you expect to happen?
Access old version of the pub

### What URL can we use to see the issue?
https://notes.knowledgefutures.org/pub/p36ckkb2/draft

### What browser/operating system were you using?
chrome Version 90.0.4430.93
ubuntu 20.04

===

### Have any screenshots? (Attach them by dragging the image here)
```
[0] TypeError: Invalid date
[0]     at Object.default (/home/howebenhowe/projects/pb/node_modules/dateformat/lib/dateformat.js:39:17)
[0]     at Object.exports.formatDate (/home/howebenhowe/projects/pb/dist/server/utils/dates.js:12:67)
[0]     at renderWarning (/home/howebenhowe/projects/pb/dist/server/client/containers/Pub/PubDocument/PubHistoricalNotice.js:138:21)
[0]     at PubHistoricalNotice (/home/howebenhowe/projects/pb/dist/server/client/containers/Pub/PubDocument/PubHistoricalNotice.js:154:13)
[0]     at processChild (/home/howebenhowe/projects/pb/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
[0]     at resolve (/home/howebenhowe/projects/pb/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
[0]     at ReactDOMServerRenderer.render (/home/howebenhowe/projects/pb/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
[0]     at ReactDOMServerRenderer.read (/home/howebenhowe/projects/pb/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
[0]     at ReactMarkupReadableStream._read (/home/howebenhowe/projects/pb/node_modules/react-dom/cjs/react-dom-server.node.development.js:4041:38)
[0]     at ReactMarkupReadableStream.Readable.read (_stream_readable.js:491:10)
[0]     at flow (_stream_readable.js:1000:34)
[0]     at Gzip.pipeOnDrainFunctionResult (_stream_readable.js:803:7)
[0]     at Gzip.emit (events.js:210:5)
[0]     at Gzip.EventEmitter.emit (domain.js:475:20)
[0]     at afterWrite (_stream_writable.js:498:12)
[0]     at onwrite (_stream_writable.js:488:7)
[0]     at Gzip.afterTransform (_stream_transform.js:96:3)
[0]     at Zlib.processCallback (zlib.js:571:8)
[0] Emitted 'error' event on ReactMarkupReadableStream instance at:
[0]     at emitErrorNT (internal/streams/destroy.js:92:8)
[0]     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
[0]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by gabestein** [comment]
Closing as cannot repor.
