### ISSUE TITLE
Deposit preview crashes page in some instances

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2027]
Seems to be a regression related to #1972, but I am having trouble recreating the conditions on demo or duqduq.

### What went wrong, step-by-step?
1. Try to preview by (re)-depositing this article: https://jbt.pubpub.org/dash/pub/rvmunuw3/settings
2. Blank screen of death!
3. Error:
``` 
TypeError: Cannot read properties of undefined (reading 'person_name')
    at AssignDoiPreview.tsx:104:59
    at b (AssignDoiPreview.tsx:120:26)
    at v (AssignDoiPreview.tsx:220:76)
```

### What browser/operating system were you using?

===

### Who reported this? (If not you)
Dawit

**Comment by gabestein** [comment]
Ah, figured it out. It's when a collection has no contributors. I'll take care of it.
