### ISSUE TITLE
Editor problem - iframe configuration

### ISSUE THREAD

**Issue by gabestein** [pubpub/pubpub#2241]
Appears to be a bug.

Repro: 

1. Add iFrame to a new pub
2. WSOD with console error:
```
TypeError: Cannot read properties of null (reading 'useDocumentState')
    at t.useDocumentState (globalHooks.js:12:25)
    at t.default (SimpleEditor.tsx:54:49)
    at $i (react-dom.production.min.js:153:146)
    at vs (react-dom.production.min.js:261:496)
    at uc (react-dom.production.min.js:246:265)
    at sc (react-dom.production.min.js:246:194)
    at Zs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Uo (react-dom.production.min.js:122:325)
    at Ko (react-dom.production.min.js:123:61)
    at Go (react-dom.production.min.js:122:496)
    at P (react-dom.production.min.js:287:95)
    at Yt (react-dom.production.min.js:68:371)
    at HTMLDocument.r (helpers.js:71:23)
```

### Discussed in https://github.com/pubpub/pubpub/discussions/2239

<div type='discussions-op-text'>

<sup>Originally posted by **kyledenlinger** September  8, 2022</sup>
A couple, possibly related, issues regarding media embeds. I've created separate threads but will link to both in comments.

Something's wrong with iframe embeds. After embedding an iframe, I can't get to the media tools to configure the iframe. Clicking on the iframe itself or on the media tools when focused on the iframe just throws a blank screen. A workaround is to insert an image using the media tools, then I'm able to access the media tools for the iframe. </div>

**Comment by gabestein** [comment]
Fixed in #2221
