### ISSUE TITLE
Unable to start on clean clone

### ISSUE THREAD

**Issue by kkukshtel** [pubpub/pubpub#277]
Ran ```npm install``` and then ```npm start``` and am getting this:

```
Error: Cannot find module './config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/kyle/Workspace/pubpub/server/models.js:4:2)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at loader (/Users/kyle/Workspace/pubpub/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/kyle/Workspace/pubpub/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
```

Anything I'm doing wrong or missing?

**Comment by kkukshtel** [comment]
Ah cool, thank you! Is there any documentation that is up to date or even something simple that can be used to write a proper README for? I'd be happy to help.

**Comment by gabestein** [comment]
We just did a major overhaul of PubPub. We still aren't really in a place to support self-installs quite yet, but it should technically be possible by setting up all of the services listed in the [example config file](https://github.com/pubpub/pubpub/server/config.sample.js) and renaming to `config.js`. If you're still interested in trying to setup your own install, by all means give it a shot and let us know how it goes. Until then, I'm going to close this issue. It's on our longer-term roadmap to support self-install via Docker with minimal config.
